name:                trinity
version:             0.1.0.0
github:              "Hexirp/trinity"
license:             BSD3
author:              "Hexirp"
maintainer:          "hexirp@gmail.com"
copyright:           "(C) Hexirp 2021"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Software

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/Hexirp/trinity#readme>

dependencies:
- base >= 4.7 && < 4.14
- containers >= 0.6.2.1 && < 0.7
- bytestring >= 0.10.10.1 && < 0.11
- time >= 1.9.3 && < 1.10
- uuid >= 1.3.13 && < 1.4

library:
  source-dirs: src

executables:
  trinity-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - trinity

tests:
  trinity-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - trinity
